Repository uliegecsm/kokkos-utils, pull requests merged in 2024-09, with the labels that each got.

#15 update: `Kokkos` 4.4.00
  CMakeLists.txt
  include/kokkos-utils/array/compare.hpp
  tests/view/test_extents.cpp
  version.json
Labels: update, kokkos

#17 docker(cuda): update to 12.6.0
  .github/workflows/build.yml
Labels: cuda

#18 cmake(tests): rename `TEST_NAME` to `NAME`
  tests/CMakeLists.txt
  tests/atomics/CMakeLists.txt
  tests/concepts/CMakeLists.txt
  tests/impl/CMakeLists.txt
  tests/view/CMakeLists.txt
Labels: enhancement
